### ISSUE TITLE
build/core/product_config.mk:256: *** No matches for product "aosp_arm".  Stop.

### ISSUE THREAD

**Issue by PeterHindes** [AospExtended-Devices/device_motorola_potter#1]
During ```lunch aosp_potter-userdebug``` on the 8.1.x and 9.x branch of both manifest and potter the error ```Can't find toolchain for unknown architecture: 
build/core/product_config.mk:256: *** No matches for product "aosp_arm".  Stop.``` is repeated multiple times and then lunch fails.

**Comment by PeterHindes** [comment]
This happens on my system running Ubuntu 14.04.5 LTS

**Comment by whofixx** [comment]
yes i get same error too
